### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by necrophonic** [companieshouse/MojoX-Plugin-AnyCache#2]
Need to be able to do:
- delete key
- set ttl (either separately or as part of a set - both would be nice)

Desirable
- get ttl (if possible - may be too much to get memcached to do it)
- increment / decrement

**Comment by ian-kent** [comment]
Done.

```
$cache->set('key', 'value', ttl);
$cache->set('key', 'value', ttl, sub { });

my $ttl = $cache->ttl('key');
$cache->ttl('key', sub { my $ttl = shift });
```

The `ttl` method returns the remaining TTL, not the original TTL.

It's emulated on Memcached backends - first need to set get_ttl_support, e.g.

```
$cache->backend->get_ttl_support(1);
```
