### ISSUE TITLE
Fails with perls < 5.14

### ISSUE THREAD

**Issue by andk** [companieshouse/MojoX-Plugin-AnyCache#5]
As per subject. Best illustrated in the matrix:

http://matrix.cpantesters.org/?dist=MojoX-Plugin-AnyCache%200.02

Sample fail report:

http://www.cpantesters.org/cpan/report/41276707

HTH && Thanks,

(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by ian-kent** [comment]
Thanks, looks like its package syntax in test files which use `package Name {}` instead of `package Name;`
